let datitos = [
  {
    Empresa: "EMPRESA MINERA SAN CRISTOBAL S.A.",
    Capital: -82,
    Deuda: 0,
    "Saldo IED": 1018,
  },
  {
    Empresa: "REPSOL E&P DE BOLIVIA S.A.",
    Capital: -13,
    Deuda: 0,
    "Saldo IED": 665,
  },
  {
    Empresa: "REPSOL BOLIVIA S.A.",
    Capital: -163,
    Deuda: 0,
    "Saldo IED": 635,
  },
  {
    Empresa: "YPFB ANDINA S.A.",
    Capital: -12,
    Deuda: 0,
    "Saldo IED": 621,
  },
  {
    Empresa:
      "COMPAÑÍA BOLIVIANA DE ENERGÍA ELÉCTRICA S.A. - BOLIVIAN POWER COMPANY LIMITED (COBEE)",
    Capital: 8,
    Deuda: 0,
    "Saldo IED": 397,
  },
  {
    Empresa: "PAE OIL & GAS BOLIVIA LTDA (PAE E&P SUC BOLIVIA)",
    Capital: 11,
    Deuda: 0,
    "Saldo IED": 380,
  },
  {
    Empresa: "PETROBRAS BOLIVIA S.A",
    Capital: -1,
    Deuda: 0,
    "Saldo IED": 370,
  },
  {
    Empresa: "TOTAL EXPLORACION &PRODUCTION BOLIVIE S.A.",
    Capital: -10,
    Deuda: 0,
    "Saldo IED": 337,
  },
  {
    Empresa: "CERVECERIA BOLIVIANA NACIONAL",
    Capital: 27,
    Deuda: -1,
    "Saldo IED": 301,
  },
  {
    Empresa: "GAS TRANSBOLIVIANO S.A.",
    Capital: 4,
    Deuda: 0,
    "Saldo IED": 288,
  },
  {
    Empresa: "SOCIEDAD BOLIVIANA DE CEMENTO  S.A. ( SOBOCE )",
    Capital: 10,
    Deuda: 0,
    "Saldo IED": 278,
  },
  {
    Empresa: "GP EXPLORACIÓN Y PRODUCCIÓN SL - SUC BOLIVIA",
    Capital: 10,
    Deuda: -12,
    "Saldo IED": 255,
  },
  {
    Empresa: "TELEFONIA CELULAR DE BOLIVIA TIGO",
    Capital: -13,
    Deuda: 10,
    "Saldo IED": 237,
  },
  {
    Empresa: "BANCO DE CRÉDITO DE BOLIVIA S.A.",
    Capital: -8,
    Deuda: 0,
    "Saldo IED": 202,
  },
  {
    Empresa: "INDUSTRIAS DE ACEITE S.A. FINO",
    Capital: -12,
    Deuda: 0,
    "Saldo IED": 188,
  },
  {
    Empresa: "NUEVATEL PCS DE BOLIVIA S.A.  VIVA",
    Capital: -20,
    Deuda: 0,
    "Saldo IED": 188,
  },
  {
    Empresa: "BANCO SOLIDARIO",
    Capital: 0,
    Deuda: 0,
    "Saldo IED": 172,
  },
  {
    Empresa: "SHELL (BG) BOLIVIA CORPORATION, SUCURSAL BOLIVIA",
    Capital: 0,
    Deuda: 10,
    "Saldo IED": 166,
  },
  {
    Empresa: "PDVSA BOLIVIA S.A.",
    Capital: 3,
    Deuda: 0,
    "Saldo IED": 146,
  },
  {
    Empresa: "BANCO FIE S.A.",
    Capital: 6,
    Deuda: 0,
    "Saldo IED": 142,
  },
  {
    Empresa: "BANCO PRODEM S.A.",
    Capital: 0,
    Deuda: 0,
    "Saldo IED": 136,
  },
  {
    Empresa: "PIL ANDINA S.A.",
    Capital: -1,
    Deuda: -3,
    "Saldo IED": 98,
  },
  {
    Empresa: "PETREX S.A. SUCURSAL BOLIVIA",
    Capital: -4,
    Deuda: 2,
    "Saldo IED": 97,
  },
  {
    Empresa: "FERROVIARIA ORIENTAL",
    Capital: 0,
    Deuda: 0,
    "Saldo IED": 90,
  },
  {
    Empresa: "EMPRESA MINERA MANQUIRI S.A.",
    Capital: 5,
    Deuda: -4,
    "Saldo IED": 81,
  },
  {
    Empresa: "IMCRUZ",
    Capital: 1,
    Deuda: 0,
    "Saldo IED": 80,
  },
  {
    Empresa: "TRENES CONTINENTALES S.A.",
    Capital: 2,
    Deuda: 0,
    "Saldo IED": 79,
  },
  {
    Empresa: "SINCHI WAYRA S.A.",
    Capital: -3,
    Deuda: 32,
    "Saldo IED": 77,
  },
  {
    Empresa: "HANSA LTDA.",
    Capital: 0,
    Deuda: 0,
    "Saldo IED": 75,
  },
  {
    Empresa: "UNILEVER ANDINA BOLIVIA S.A.",
    Capital: 3,
    Deuda: 0,
    "Saldo IED": 67,
  },
  {
    Empresa: "ITACAMBA CEMENTO S.A.",
    Capital: -4,
    Deuda: 0,
    "Saldo IED": 60,
  },
  {
    Empresa: "FINNING BOLIVIA S.A.",
    Capital: 0,
    Deuda: 0,
    "Saldo IED": 58,
  },
  {
    Empresa: "HIDROELECTRICA BOLIVIANA",
    Capital: 1,
    Deuda: 0,
    "Saldo IED": 53,
  },
  {
    Empresa: "PRAXAIR BOLIVIA SRL",
    Capital: 1,
    Deuda: 0,
    "Saldo IED": 48,
  },
  {
    Empresa: "PAN AMERICAN SILVER (BOLIVIA) S.A.",
    Capital: -3,
    Deuda: 0,
    "Saldo IED": 46,
  },
  {
    Empresa: "COMVERSA SA. (COMPAÑÍA DE INVERSIONES SA.) Holding",
    Capital: -1,
    Deuda: 0,
    "Saldo IED": 43,
  },
  {
    Empresa: "COMPAÑÍA INDUSTRIAL DE TABACOS S.A.",
    Capital: 3,
    Deuda: 0,
    "Saldo IED": 42,
  },
  {
    Empresa: "EMBOL S.A.",
    Capital: -18,
    Deuda: 0,
    "Saldo IED": 39,
  },
  {
    Empresa: "HUAWEI TECHNOLOGIES (BOLIVIA) S.R.L.",
    Capital: 21,
    Deuda: 0,
    "Saldo IED": 38,
  },
  {
    Empresa: "KIMBERLY BOLIVIA S.A.",
    Capital: 2,
    Deuda: 2,
    "Saldo IED": 37,
  },
  {
    Empresa: "GASORIENTE BOLIVIANO LTDA. GOB LTDA.",
    Capital: 0,
    Deuda: 0,
    "Saldo IED": 36,
  },
  {
    Empresa: "AXS BOLIVIA S.A.",
    Capital: 0,
    Deuda: 0,
    "Saldo IED": 36,
  },
  {
    Empresa: "SOCIEDAD MINERA ILLAPA S.A.",
    Capital: -18,
    Deuda: 0,
    "Saldo IED": 35,
  },
  {
    Empresa: "LABORATORIOS BAGO LTDA",
    Capital: 2,
    Deuda: 0,
    "Saldo IED": 35,
  },
  {
    Empresa: "CARGILL BOLIVIA S.A.",
    Capital: 3,
    Deuda: -4,
    "Saldo IED": 34,
  },
  {
    Empresa: "INTERCONEXIÓN ELÉCTRICA ISA BOLIVIA S.A.",
    Capital: -3,
    Deuda: 0,
    "Saldo IED": 31,
  },
  {
    Empresa: "ALIANZA COMPAÑÍA DE SEGUROS Y REASEGUROS S.A.E.M.A.",
    Capital: 3,
    Deuda: 0,
    "Saldo IED": 30,
  },
  {
    Empresa: "AIR BP BOLIVIA S.A.",
    Capital: -1,
    Deuda: 0,
    "Saldo IED": 28,
  },
  {
    Empresa: "PLASMAR S.A. (TIGRE)",
    Capital: 4,
    Deuda: 0,
    "Saldo IED": 27,
  },
  {
    Empresa: "BAKER HUGHES INT. BRANCHES INC. SUC. BOLIVIA (DIV. ATLAS)",
    Capital: 7,
    Deuda: 0,
    "Saldo IED": 26,
  },
  {
    Empresa: "PLUSPETROL BOLIVIA CORPORATION S.A.",
    Capital: 1,
    Deuda: 1,
    "Saldo IED": 24,
  },
  {
    Empresa: "GWB INVERSIONES S.A.",
    Capital: 0,
    Deuda: 0,
    "Saldo IED": 22,
  },
  {
    Empresa: "BANCO DE DESARROLLO PRODUCTIVO SAM - BDP",
    Capital: 0,
    Deuda: 0,
    "Saldo IED": 18,
  },
  {
    Empresa: "LA PAPELERA",
    Capital: 0,
    Deuda: 0,
    "Saldo IED": 16,
  },
  {
    Empresa: "Archer DLS Corporation",
    Capital: -1,
    Deuda: 0,
    "Saldo IED": 15,
  },
  {
    Empresa: "PHARMA INVESTI SRL",
    Capital: 1,
    Deuda: 0,
    "Saldo IED": 13,
  },
  {
    Empresa: "PINTURAS CORAL DE BOLIVIA LTDA.",
    Capital: 1,
    Deuda: 0,
    "Saldo IED": 13,
  },
  {
    Empresa: "FUTURO DE BOLIVIA AFP",
    Capital: -2,
    Deuda: 0,
    "Saldo IED": 12,
  },
  {
    Empresa: "MAXAM FANEXA S.A.M.",
    Capital: 0,
    Deuda: 0,
    "Saldo IED": 11,
  },
  {
    Empresa: "SAN CRISTOBAL TRANSMISORA DE ELECTRICIDAD",
    Capital: 1,
    Deuda: 0,
    "Saldo IED": 11,
  },
  {
    Empresa: "VINTAGE PETROLEUM BOLIVIANA LTD. SUCURSAL BOLIVIA",
    Capital: 1,
    Deuda: 0,
    "Saldo IED": 11,
  },
  {
    Empresa: "TECNOFARMA S.A.",
    Capital: 2,
    Deuda: 0,
    "Saldo IED": 11,
  },
  {
    Empresa: "ALIANZA VIDA SEGUROS Y REASEGUROS S.A.",
    Capital: 1,
    Deuda: 0,
    "Saldo IED": 9,
  },
  {
    Empresa: "EMPRESA DE SERVICIO DE PAGO MOVIL EFECTIVO",
    Capital: 1,
    Deuda: 0,
    "Saldo IED": 9,
  },
  {
    Empresa: "PRODUCTOS SANCELA DEL PERÚ (SUCURSAL BOLIVIA)",
    Capital: 0,
    Deuda: -1,
    "Saldo IED": 8,
  },
  {
    Empresa: "BUPA INSURANCE BOLIVIA S.A.",
    Capital: 0,
    Deuda: 0,
    "Saldo IED": 7,
  },
  {
    Empresa: "DEKMA BOLIVIA S.A.",
    Capital: -1,
    Deuda: -1,
    "Saldo IED": 7,
  },
  {
    Empresa: "BBVA PREVISIÓN AFP S.A.",
    Capital: 2,
    Deuda: 0,
    "Saldo IED": 7,
  },
  {
    Empresa:
      "EMPRESA DE SERVICIOS INMOBILIARIOS Y DE MANTENIMIENTO S.A. ESIMSA",
    Capital: 0,
    Deuda: 0,
    "Saldo IED": 7,
  },
  {
    Empresa: "GIROS ELECTRÓNICOS ELEGIR S.R.L.",
    Capital: -1,
    Deuda: 0,
    "Saldo IED": 7,
  },
  {
    Empresa: "AGRICULTURA AVANZADA DE AMERICA INTERNACIONAL CORPORATION AAA",
    Capital: 0,
    Deuda: 0,
    "Saldo IED": 6,
  },
  {
    Empresa: "ARCOR ALIMENTOS BOLIVIA SA",
    Capital: 1,
    Deuda: -1,
    "Saldo IED": 6,
  },
  {
    Empresa: "YANBAL DE BOLIVIA S.A.",
    Capital: -3,
    Deuda: 0,
    "Saldo IED": 6,
  },
  {
    Empresa: "CREDISEGURO S.A. SEGUROS PERSONALES",
    Capital: 0,
    Deuda: 0,
    "Saldo IED": 6,
  },
  {
    Empresa: "EMPRESA MINERA PAITITI S.A.",
    Capital: -4,
    Deuda: 10,
    "Saldo IED": 5,
  },
  {
    Empresa: "BANCO FORTALEZA",
    Capital: 0,
    Deuda: 0,
    "Saldo IED": 5,
  },
  {
    Empresa:
      'SOCIEDAD INDUSTRIAL ENERGÉTICA Y COMERCIAL ANDINA S.A. "SYNERGIA S.A.',
    Capital: 0,
    Deuda: 0,
    "Saldo IED": 4,
  },
  {
    Empresa: "OMNILIFE DE BOLIVIA S.A.",
    Capital: 1,
    Deuda: 0,
    "Saldo IED": 4,
  },
  {
    Empresa: "COLGATE PALMOLIVE BOLIVIA LTDA.",
    Capital: 1,
    Deuda: 1,
    "Saldo IED": 4,
  },
  {
    Empresa: "ARYSTA LIFESCIENCE SRL",
    Capital: 0,
    Deuda: 0,
    "Saldo IED": 4,
  },
  {
    Empresa: "BRINKS BOLIVIA",
    Capital: 0,
    Deuda: 0,
    "Saldo IED": 3,
  },
  {
    Empresa: "BAT BOLIVIA SRL",
    Capital: 0,
    Deuda: 0,
    "Saldo IED": 3,
  },
  {
    Empresa: "MONDELEZ DE ALIMENTOS",
    Capital: 0,
    Deuda: -1,
    "Saldo IED": 3,
  },
  {
    Empresa: "BRENNTAG BOLIVIA SRL",
    Capital: 0,
    Deuda: 0,
    "Saldo IED": 3,
  },
  {
    Empresa: "BANCO PYME DE LA COMUNIDAD S.A.",
    Capital: 0,
    Deuda: 0,
    "Saldo IED": 2,
  },
  {
    Empresa: "INVERSIONES TRIÁNGULO DE ORO S.A.",
    Capital: 0,
    Deuda: 0,
    "Saldo IED": 2,
  },
  {
    Empresa: "ANTALIS BOLIVIA SRL",
    Capital: 0,
    Deuda: 0,
    "Saldo IED": 2,
  },
  {
    Empresa: "CREDISEGURO S.A. SEGUROS GENERALES",
    Capital: 0,
    Deuda: 0,
    "Saldo IED": 2,
  },
  {
    Empresa: "DIMENTIONAL SODALITE LTDA. (DIESSE LTDA.)",
    Capital: 0,
    Deuda: 0,
    "Saldo IED": 2,
  },
  {
    Empresa: "SERVIAGRICOLA DEL SUR S.R.L.",
    Capital: 0,
    Deuda: 0,
    "Saldo IED": 1,
  },
  {
    Empresa: "BITUMINA INDUSTRIAL BOLIVIA S.A.",
    Capital: 0,
    Deuda: 2,
    "Saldo IED": 1,
  },
  {
    Empresa: "GLENCORE BOLIVIA LTDA.",
    Capital: 0,
    Deuda: 0,
    "Saldo IED": 1,
  },
  {
    Empresa: "GSH BOLIVIA SRL",
    Capital: 0,
    Deuda: 0,
    "Saldo IED": 1,
  },
  {
    Empresa: "SMC PNEUMATICS BOLIVIA SRL",
    Capital: 0,
    Deuda: 0,
    "Saldo IED": 1,
  },
  {
    Empresa: "SABRE INTERNATIONAL LLC BOLIVIA",
    Capital: 0,
    Deuda: 0,
    "Saldo IED": 1,
  },
  {
    Empresa: "INVERSIONES DORMESON BOLIVIA S.A.",
    Capital: 0,
    Deuda: 0,
    "Saldo IED": 1,
  },
  {
    Empresa: "BISA LEASING",
    Capital: 0,
    Deuda: 0,
    "Saldo IED": 1,
  },
  {
    Empresa: "JACHA INTI INDUSTRIAL S.A.",
    Capital: 0,
    Deuda: 0,
    "Saldo IED": 1,
  },
  {
    Empresa: "EPIROC S.A.",
    Capital: 0,
    Deuda: 0,
    "Saldo IED": 1,
  },
  {
    Empresa: "SAMSUNG ELECTRONICS CHILE LDTA. SUC. BOLIVIA",
    Capital: 0,
    Deuda: 0,
    "Saldo IED": 1,
  },
  {
    Empresa: "COMPAÑÍA MINERA AMAZONA BOLIVIA - COMABOL S.A.",
    Capital: 0,
    Deuda: 0,
    "Saldo IED": 1,
  },
  {
    Empresa: "MEDITERRANEAN SHIPPING COMPANY BOLIVIA LTDA.",
    Capital: 0,
    Deuda: 0,
    "Saldo IED": 1,
  },
  {
    Empresa: "CONSTRUCCIONES SEPCON SRL",
    Capital: 0,
    Deuda: 1,
    "Saldo IED": 1,
  },
  {
    Empresa: "FACTURACIÓN INMEDIATA FIMM SRL",
    Capital: 0,
    Deuda: 0,
    "Saldo IED": 1,
  },
  {
    Empresa: "INVERSIONES CREDICORP BOLIVIA S.A.",
    Capital: -3,
    Deuda: 0,
    "Saldo IED": 1,
  },
  {
    Empresa: "AVANTICA TECHNOLOGIES",
    Capital: 0,
    Deuda: 0,
    "Saldo IED": 0,
  },
  {
    Empresa: "KUEHNE + NAGEL LTDA.",
    Capital: 0,
    Deuda: 0,
    "Saldo IED": 0,
  },
  {
    Empresa: "BIOGENESIS BAGO BOLIVIA S.A.",
    Capital: 0,
    Deuda: 1,
    "Saldo IED": 0,
  },
  {
    Empresa: "EQUANET S.R.L.",
    Capital: 0,
    Deuda: 0,
    "Saldo IED": 0,
  },
  {
    Empresa: "NEXUS TECHNOLOGY BOLIVIA S.A.",
    Capital: 0,
    Deuda: 0,
    "Saldo IED": 0,
  },
  {
    Empresa: "TETRAPACK",
    Capital: 0,
    Deuda: 0,
    "Saldo IED": 0,
  },
  {
    Empresa: "INCLAM S.A. SUCURSAL BOLIVIA",
    Capital: 0,
    Deuda: 0,
    "Saldo IED": 0,
  },
  {
    Empresa: "CONSTRUCCIONES RUBAU SA SUCURSAL BOLIVIA",
    Capital: 0,
    Deuda: 0,
    "Saldo IED": 0,
  },
  {
    Empresa: "OLSA BOLIVIA CORREDORES DE REASEGUROS S.A.",
    Capital: 0,
    Deuda: 0,
    "Saldo IED": 0,
  },
  {
    Empresa: "CSRA BOLIVIA SRL",
    Capital: 0,
    Deuda: 0,
    "Saldo IED": 0,
  },
  {
    Empresa: "SERVICIOS JARDECOM S.A.",
    Capital: 0,
    Deuda: 0,
    "Saldo IED": 0,
  },
  {
    Empresa: "TELEFERICOS DOPPELMAYER BOLIVIA S.A.",
    Capital: 1,
    Deuda: 3,
    "Saldo IED": 0,
  },
  {
    Empresa: "QSI INDUSTRIAL  BOLIVIA S.A.",
    Capital: -2,
    Deuda: 0,
    "Saldo IED": 0,
  },
  {
    Empresa: "ENGELS MERKEL",
    Capital: 0,
    Deuda: 0,
    "Saldo IED": 0,
  },
  {
    Empresa: "BANCO PYME ECOFUTURO",
    Capital: 0,
    Deuda: 0,
    "Saldo IED": 0,
  },
  {
    Empresa: "GEOLOG MUD LOGGING BOLIVIA LTDA. (NEW 2012)",
    Capital: 0,
    Deuda: 0,
    "Saldo IED": 0,
  },
  {
    Empresa: "PROINTEC S.A. SUCURSAL BOLIVIA",
    Capital: 0,
    Deuda: 0,
    "Saldo IED": 0,
  },
  {
    Empresa: "CISNEROS INTERACTIVE BOLIVIA S.R.L.",
    Capital: -1,
    Deuda: 0,
    "Saldo IED": 0,
  },
  {
    Empresa: "LA SANTE S.R.L.",
    Capital: 0,
    Deuda: 0,
    "Saldo IED": -1,
  },
  {
    Empresa: "COMERCIALIZADORA EMASA BOLIVIA S.R.L.",
    Capital: 0,
    Deuda: 0,
    "Saldo IED": -1,
  },
  {
    Empresa: "IMPORTADORA Y DISTRIBUIDORA INTB SRL",
    Capital: 0,
    Deuda: 0,
    "Saldo IED": -1,
  },
  {
    Empresa: "REPSOL EXPLORACION ATLAS",
    Capital: 0,
    Deuda: 0,
    "Saldo IED": -1,
  },
  {
    Empresa: "IPSOS APOYO Y OPINION Y MERCADO BOLIVIA S.A.",
    Capital: 0,
    Deuda: 0,
    "Saldo IED": -2,
  },
  {
    Empresa: "INGENER S.A. SUCURSAL BOLIVIA",
    Capital: 0,
    Deuda: 0,
    "Saldo IED": -2,
  },
  {
    Empresa: "TSK ELECTRONICA Y ELECTRICIDAD S.A. SUCURSAL BOLIVIA",
    Capital: 8,
    Deuda: 10,
    "Saldo IED": -32,
  },
  {
    Empresa:
      "SINOPEC INTERNATIONAL PETROLEUM SERVICE ECUADOR S.A (SUCURSAL BOLIVIA)",
    Capital: -1,
    Deuda: 2,
    "Saldo IED": -88,
  },
];
